before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake test_app"
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
script:
  - "export DISPLAY=:99.0"
  - "alias set_gemfile='export BUNDLE_GEMFILE=\"`pwd`/Gemfile\"'"
  - "cd api; set_gemfile; bundle install --quiet; bundle exec rspec spec"
  - "cd ../auth; set_gemfile; bundle install --quiet; bundle exec rspec spec"
  - "cd ../core; set_gemfile; bundle install --quiet; bundle exec rspec spec"
  - "cd ../dash; set_gemfile; bundle install --quiet; bundle exec rspec spec"
  - "cd ../promo; set_gemfile; bundle install --quiet; bundle exec rspec spec"

notifications:
  email:
    - joahking@gmail.com
branches:
  only:
    - travis-fixes_1455-drag-and-drops-do-not-go-above-table-headers
rvm:
  - 1.8.7
  - 1.9.3
